# ┌──────────────────────────┐
# │                          │
# │     ░▀█▀░█▄█░█░█░█░█     │
# │     ░░█░░█░█░█░█░▄▀▄     │
# │     ░░▀░░▀░▀░▀▀▀░▀░▀     │
# │                          │
# └──────────────────────────┘

set -s escape-time 0
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

# Set default shell
set-option -g default-shell $SHELL

# Set true color support
set-option -sa terminal-features ',xterm-256color:RGB'
set-option -sa terminal-overrides ",xterm*:Tc"

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Set mouse mode on
set -g mouse on

# Additional keybindings
bind d detach-client
bind n command-prompt -p "New session name:" "new-session -s '%%'"
bind-key b set-option status

# Window navigation
bind H previous-window
bind L next-window

# Pane navigation (compatible with vim-tmux-navigator)
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# Pane resizing
bind -r Left resize-pane -L 5
bind -r Right resize-pane -R 5
bind -r Up resize-pane -U 5
bind -r Down resize-pane -D 5

# Start window numbering at 1
set -g base-index 1
setw -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on
set -g escape-time 0         # zero-out escape time delay

# Theme: borders
set -g pane-active-border-style 'fg=#BE4277'
set -g pane-border-style 'fg=#161616'

# Status bar configuration (moved to the bottom)
set -g status on
set -g status-position top
set -g status-justify centre
# set -g status-interval 1
set -g status-style bg=default,fg=brightblack

# Status left and right formatting
set -g status-left "#[fg=#8D8D8D,bold][#S]"
set -g status-right "#[fg=#7D374E,bold]#{?client_prefix,#[reverse]<Prefix>#[noreverse] ,}#[fg=brightblack,bold]#{window_name}"

# Theme: status (windows)
set -g window-status-format "#[fg=#B04D6E]●"
set -g window-status-current-format "#[fg=#BE4277]●"
set -g window-status-current-style "#{?window_zoomed_flag,fg=#D55FA3,fg=#FBB6D0}"
set -g window-status-bell-style "fg=#D55FA3,nobold"
set -g status-justify absolute-centre

# name window before creating it
# bind c command-prompt -p "Window name:" "new-window -n '%%'"

# Set vi-mode
set-window-option -g mode-keys vi

# Copy mode
set -g set-clipboard on
setw -g mode-style 'fg=#DD4D8B bg=#000000 bold'

set -g allow-passthrough on

# Activity monitoring (disabled to remove highlights)
setw -g monitor-activity off
set -g visual-activity off
set -g visual-bell off

# Window splitting
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind G new-window -n 'lazygit' -c "#{pane_current_path}" lazygit

# Plugin manager
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

run '~/.tmux/plugins/tpm/tpm'
