# hyprlauncher config

general {
    grab_focus = 1
}

cache {
    enabled = 1
}

ui {
    window_size = 250 80   # width height in pixels (default: 400 260)
}

finders {
    default_finder = desktop      # desktop | unicode | math | font

    desktop_prefix =              # prefix to force desktop search (empty = default)
    unicode_prefix = .            # .heart  .arrow
    math_prefix    = =            # =2+2  =sqrt(16)
    font_prefix    = '            # search fonts

    desktop_launch_prefix =       # prepend a command before every app launch
    desktop_icons     = 0         # show app icons: 1 = yes, 0 = no
}
