source = ~/.config/hypr/autostart.sh
source = ~/.config/hypr/xf86.conf
source = ~/.config/hypr/animations.conf
source = ~/.config/hypr/theme.conf
source = ~/.config/hypr/binds.conf
source = ~/.config/hypr/rules.conf
#source = ~/.config/hypr/gtk.sh


# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

# Some default env vars.
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = GDK_BACKEND,wayland
env = QT_QPA_PLATFORM=wayland
env = QT_QPA_PLATFORMTHEME=qt5ct
env = XCURSOR_SIZE,26
env = WLR_NO_HARDWARE_CURSOR, 1

# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░
input {
  kb_layout = us
  follow_mouse = 1
  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

