# @MR5OBOT hyprland cfg

# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

# See https://wiki.hyprland.org/Configuring/Keywords/
source = $HOME/.config/hypr/autostart.sh
source = $HOME/.config/hypr/configs/Animations.conf
source = $HOME/.config/hypr/configs/ENVariales.conf
source = $HOME/.config/hypr/configs/Keymaps.conf
source = $HOME/.config/hypr/configs/Theme.conf
source = $HOME/.config/hypr/configs/WindowRules.conf
# source = $HOME/.config/hypr/configs/Monitors.conf

# Set programs that you use
$terminal = kitty
$fileManager = thunar


# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

# See https://wiki.hyprland.org/Configuring/Variables/
input {
  kb_layout = us
  follow_mouse = 1
  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

xwayland {
    force_zero_scaling = true
}

misc {
  vrr = 0
#  focus_on_activate = true
  # mouse_move_enables_dpms = true
  enable_swallow = true # swallowing terminal window after open apps from it.
  swallow_regex = ^(kitty)$
  disable_hyprland_logo = true
  # disable_splash_rendering = true
  force_default_wallpaper = 0
}

# ----------------------------------------------------- 
# Environment for xdg-desktop-portal-hyprland
# ----------------------------------------------------- 
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

