# @MR5OBOT hyprland cfg

# █░░ ▄▀█ █░█ █▄░█ █▀▀ █░█
# █▄▄ █▀█ █▄█ █░▀█ █▄▄ █▀█

# See https://wiki.hyprland.org/Configuring/Keywords/
# source = $HOME/.config/hypr/configs/ENVariales.conf
# source = $HOME/.config/hypr/autostart.sh
source = $HOME/.config/hypr/configs/Animations.conf
source = $HOME/.config/hypr/configs/Keymaps.conf
source = $HOME/.config/hypr/configs/Theme.conf
source = $HOME/.config/hypr/configs/WindowRules.conf
# source = $HOME/.config/hypr/configs/Monitors.conf

# -----------------------------------------------------
# Set environment variables for XDG Desktop Portal
# -----------------------------------------------------
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = dbus-update-activation-environment --all

# Set GTK Theme
exec-once = hyprctl setcursor Future-dark-cursors 24

# Autostart Applications (same as in your script)
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = nm-applet --indicator
exec-once = dunst
exec-once = devify
exec-once = hypridle
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Set Wallpaper
exec-once = swaybg -i ~/Pictures/wallpapers/MR5OBOT.jpg

# Launch Scripts (same as in your script)
exec-once = sleep 2 && $SCRIPTS/autostart/xdgportals.sh
exec-once = $SCRIPTS/autostart/pipewire_check.sh
exec-once = $SCRIPTS/autostart/toggle-waybar.sh
# exec-once = $SCRIPTS/autostart/gtk.sh
exec-once = $SCRIPTS/autostart/Hypridle.sh
exec-once = $SCRIPTS/autostart/BAT-check.sh

# Set programs that you use
$terminal = kitty
$fileManager = thunar

# █ █▄░█ █▀█ █░█ ▀█▀
# █ █░▀█ █▀▀ █▄█ ░█░

# See https://wiki.hyprland.org/Configuring/Variables/
input {
  kb_layout = us
  follow_mouse = 1
  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
}

xwayland {
    force_zero_scaling = true
}

misc {
  vrr = 0
#  focus_on_activate = true
  # mouse_move_enables_dpms = true
  enable_swallow = true # swallowing terminal window after open apps from it.
  swallow_regex = ^(kitty)$
  disable_hyprland_logo = true
  # disable_splash_rendering = true
  force_default_wallpaper = 0
}
