## ░█▀▀░▀█▀░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀█
## ░▀▀█░░█░░█▀█░█▀▄░▀▀█░█▀█░░█░░█▀▀
## ░▀▀▀░░▀░░▀░▀░▀░▀░▀▀▀░▀░▀░▀▀▀░▀░░

add_newline = false

format = '''
[$directory](bold red)[$git_branch](bold green)[$python](yellow bold)[$cmd_duration](cyan)
$character
'''

[character]
success_symbol = '[➜](bold green)' # Using ➜ as the prompt symbol
error_symbol = '[➜](bold red)'

[python]
format = '[λ $virtualenv ]($style)' # Using λ to indicate Python venv
style = 'yellow bold'
detect_extensions = ['py']
detect_folders = ['env', 'venv', '.venv']

[cmd_duration]
min_time = 500
format = '[⏱ $duration](cyan)'

[package]
disabled = true
