$SCRIPTS=~/.config/hypr/scripts

# Critical Services
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Set environment variables for XDG Desktop Portal
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = $SCRIPTS/autostart/pipewire_check.sh >> ~/.hyprland-autostart.log 2>&1

# Set Wallpaper
exec-once = swaybg -i ~/Pictures/wallpapers/MR5OBOT.jpg

# removed not impo i think
# exec-once = dbus-update-activation-environment --all

# Set cursor Theme
# exec-once = hyprctl setcursor Future-dark-cursors 24
exec-once = hyprctl setcursor volantes_light_cursors 26

# Applications
exec-once = sleep 1 && nm-applet --indicator
exec-once = sleep 1 && dunst
exec-once = sleep 1 && devify
exec-once = hypridle
exec-once = clipse -listen

# Launch Scripts
exec-once = $SCRIPTS/autostart/gtk.sh >> ~/.hyprland-autostart.log 2>&1 # set theme based on gtk-3.0 dir
# exec-once = $SCRIPTS/autostart/Hypridle.sh >> ~/.hyprland-autostart.log 2>&1
exec-once = sleep 1 && $SCRIPTS/autostart/xdgportals.sh >> ~/.hyprland-autostart.log 2>&1
exec-once = sleep 1 && $SCRIPTS/autostart/toggle-waybar.sh >> ~/.hyprland-autostart.log 2>&1
exec-once = sleep 3 && $SCRIPTS/autostart/BAT-check.sh >> ~/.hyprland-autostart.log 2>&1


