# Autostart

$SCRIPTS = ~/.config/hypr/scripts

# Critical Services
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # Set environment variables for XDG Desktop Portal
# exec-once = dbus-update-activation-environment --systemd --all
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Daemons
exec-once = hyprpaper
exec-once = dunst
exec-once = nm-applet --indicator
exec-once = blueman-applet
# exec-once = clipse -listen
exec-once = wl-paste --watch cliphist store
exec-once = wl-clip-persist --clipboard regular
exec-once = devify
exec-once = hypridle

# Set cursor Theme
# exec-once = hyprctl setcursor volantes_light_cursors 26

# Launch Scripts
exec-once = $SCRIPTS/autostart/gtk.sh >> ~/.hyprland-autostart.log 2>&1
exec-once = $SCRIPTS/autostart/xdgportals.sh >> ~/.hyprland-autostart.log 2>&1
exec-once = $SCRIPTS/autostart/toggle-waybar.sh >> ~/.hyprland-autostart.log 2>&1
exec-once = $SCRIPTS/autostart/BAT-check.sh >> ~/.hyprland-autostart.log 2>&1
# exec-once = $SCRIPTS/autostart/Hypridle.sh >> ~/.hyprland-autostart.log 2>&1
