# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

# Backend Variables
env = GDK_BACKEND,wayland,x11  # Prefer Wayland, fallback to X11  
env = CLUTTER_BACKEND,wayland  # Force Clutter to use Wayland  
env = SDL_VIDEODRIVER,wayland  # SDL2 on Wayland (set to x11 if issues)  

# XDG Specs  
env = XDG_CURRENT_DESKTOP,Hyprland  
env = XDG_SESSION_TYPE,wayland  
env = XDG_SESSION_DESKTOP,Hyprland  

# Qt Variables  
env = QT_AUTO_SCREEN_SCALE_FACTOR,1  # Auto scale for HiDPI  
env = QT_QPA_PLATFORM,wayland;xcb  # Prefer Wayland, fallback to X11  
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1  # Remove Qt window borders  
env = QT_QPA_PLATFORMTHEME,qt5ct  # Use qt5ct for theming  

# Firefox  
env = MOZ_ENABLE_WAYLAND,1  

# Brave  
env = OZONE_PLATFORM,wayland  
env = OZONE_PLATFORM_HINT,auto  

# Theming  
env = GTK_THEME,paradice  # Set GTK theme  
env = XCURSOR_THEME,Future-dark-cursors  # Cursor theme  
env = XCURSOR_SIZE,24  # Cursor size  
