# █▀▀ █▄░█ █░█
# ██▄ █░▀█ ▀▄▀

# Backend Variables
env = GDK_BACKEND,wayland,x11,* # GTK: Use wayland if available. If not: try x11, then any other GDK backend.
env = CLUTTER_BACKEND,wayland  # Clutter package already has wayland enabled, this variable will force Clutter applications to try and use the Wayland backend  
env = SDL_VIDEODRIVER,wayland  # Run SDL2 applications on Wayland. Remove or set to x11 if games that provide older versions of SDL cause compatibility issues

# XDG Desktop Portal
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = WLR_NO_HARDWARE_CURSORS,1

# Qt Variables  
env = QT_AUTO_SCREEN_SCALE_FACTOR,1  # (From the Qt documentation) enables automatic scaling, based on the monitor’s pixel density  
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,1

# Theming  
env = GTK_THEME,paradice  # Set GTK theme  
env = XCURSOR_THEME,Future-dark-cursors  # Cursor theme  
env = XCURSOR_SIZE,24  # Cursor size  

# GDK
env = GDK_SCALE,1

# Mozilla
env = MOZ_ENABLE_WAYLAND,1

# Ozone
env = OZONE_PLATFORM,wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
