
# ▒█░▄▀ █▀▀ ▒█░░▒█ █▀▄▀█ █▀▀█ █▀▀█
# ▒█▀▄░ █▀▀ ▒█▄▄▄█ █░▀░█ █▄▄█ █░░█
# ▒█░▒█ ▀▀▀ ░░▒█░░ ▀░░░▀ ▀░░▀ █▀▀▀

# General Settings
$SCRIPTS = $HOME/.config/hypr/scripts
$mainMod = SUPER
$SCRIPT = $HOME/.config/hypr/scripts/controls

# Window Management
bind = $mainMod, Q, killactive
bind = $mainMod SHIFT, Q, exit
bind = $mainMod, F, fullscreen
bind = $mainMod, G, togglegroup
bind = $mainMod, C, centerwindow
bind = Alt, Space, togglefloating
bind = Alt, L, exec, hyprlock

# Application Launchers
bind = $mainMod, RETURN, exec, [float]kitty
bind = $mainMod, Space, exec, rofi -show drun
bind = $mainMod, N, exec, swaync-client -t
bind = $mainMod, X, exec, sh $SCRIPTS/rofi-powermenu.sh
bind = $mainMod, W, exec, sh $SCRIPTS/wallpapers/walls-picker.sh
bind = $mainMod, V, exec, kitty --class clipse -e "clipse"
# bind = $mainMod, V, exec, cliphist list | rofi -dmenu -theme ~/.config/rofi/custom/clipboard.rasi | cliphist decode | wl-copy
bind = $mainMod_SHIFT, C, exec, hyprpicker -a -n
bind = ALT, C, exec, qalculate-gtk
bind = $mainMod, T, exec, python $SCRIPTS/time-notify.py

# Waybar Controls
bind = $mainMod, K, exec, pkill -SIGUSR1 '^waybar$'
bind = $mainMod, B, exec, sh $SCRIPTS/autostart/toggle-waybar.sh

# Screenshots & Recording
bind = , Print, exec, sh $SCRIPTS/WayShot.sh
bind = $mainMod, R, exec, $SCRIPTS/recording/wf-screenRE
bind = $mainMod_SHIFT, R, exec, $SCRIPTS/recording/stop-recording

# Volume & Brightness
bind = , xf86audioraisevolume, exec, $SCRIPT/volume.sh --inc
bind = , xf86audiolowervolume, exec, $SCRIPT/volume.sh --dec
bind = , xf86AudioMicMute, exec, $SCRIPT/volume.sh --toggle-mic
bind = , xf86audioMute, exec, $SCRIPT/volume.sh --toggle

bind = , xf86MonBrightnessDown, exec, $SCRIPT/brightness.sh --dec
bind = , xf86MonBrightnessUp, exec, $SCRIPT/brightness.sh --inc

# Focus Navigation
binds {
    movefocus_cycles_fullscreen = 1
}
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, K, movefocus, u
bind = $mainMod, J, movefocus, d

# Moving Windows
bind = $mainMod_ALT, H, movewindow, l
bind = $mainMod_ALT, L, movewindow, r
bind = $mainMod_ALT, K, movewindow, u
bind = $mainMod_ALT, J, movewindow, d

# Resizing Windows
bind = $mainMod_CTRL, H, resizeactive, -20 0
bind = $mainMod_CTRL, L, resizeactive, 20 0
bind = $mainMod_CTRL, K, resizeactive, 0 -20
bind = $mainMod_CTRL, J, resizeactive, 0 20

# Workspaces
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9

# Move Windows to Workspaces
bind = $mainMod_Shift, 1, movetoworkspace, 1
bind = $mainMod_Shift, 2, movetoworkspace, 2
bind = $mainMod_Shift, 3, movetoworkspace, 3
bind = $mainMod_Shift, 4, movetoworkspace, 4
bind = $mainMod_Shift, 5, movetoworkspace, 5
bind = $mainMod_Shift, 6, movetoworkspace, 6
bind = $mainMod_Shift, 7, movetoworkspace, 7
bind = $mainMod_Shift, 8, movetoworkspace, 8
bind = $mainMod_Shift, 9, movetoworkspace, 9


# Move/Resize focused window
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow
bindm = $mainMod, Z, movewindow
# bindm = $mainMod, X, resizewindow

