
# swaync
layerrule {
    name = swaync-panel
    match:namespace = ^(swaync-control-center)$
    blur = on
    animation = slide right
}

layerrule {
    name = swaync-notif
    match:namespace = ^(swaync-notification-window)$
    blur = on
}
