
# Hyprland Configuration for GTK, Cursor, and Window Decorations

# Theme and Appearance Settings
# exec = gsettings set org.gnome.desktop.interface gtk-theme 'paradice'
#exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
#exec = gsettings set org.gnome.desktop.interface icon-theme 'Adwaita'

# Cursor Configuration
#exec = hyprctl setcursor Future-dark-cursors 24
#exec = gsettings set org.gnome.desktop.interface cursor-theme 'Future-dark-cursors'
#exec = gsettings set org.gnome.desktop.interface cursor-size 24

# Font Settings
#exec = gsettings set org.gnome.desktop.interface font-name 'NovaMono Bold Italic 10'
#exec = gsettings set org.gnome.desktop.interface document-font-name 'SF Pro Display Regular 10'
#exec = gsettings set org.gnome.desktop.interface monospace-font-name 'CaskaydiaCove Nerd Font Mono 9'
#exec = gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
#exec = gsettings set org.gnome.desktop.interface font-hinting 'full'

# Hyprland General Settings
general {
    gaps_in = 3              # Inner gaps between windows
    gaps_out = 5             # Outer gaps between windows and the screen edges
    border_size = 0          # No borders around windows
    col.active_border = 0x323232  # Active window border color
    col.inactive_border = 0x323232 # Inactive window border color
    resize_on_border = false  # Disable resizing windows via borders
    no_border_on_floating = true # No borders on floating windows
}

# Window Decoration Settings
decoration {
    rounding = 0
    
   blur {
       enabled = false
       xray = true
       special = false
       new_optimizations = true
       size = 14
       passes = 4
       brightness = 1
       noise = 0.01
       contrast = 1
       popups = true
       popups_ignorealpha = 0.6
   }
   
    # Shadow
    shadow {
        enabled = true
        ignore_window = true
        range = 5
        offset = 0 2
        render_power = 1
        color = 0xee1a1a1a
    }
}

group {
    groupbar {
        enabled = true
        font_size = 12
        height = 16
        #stacked = true
        text_color = 0xffffffff
        col.active = 0x808080FF
        col.inactive = 0x66777700
        col.locked_active = 0x66ff5500	
        col.locked_inactive = 0x66775500

        }
    misc {
            font_family	{

                }
        }
}

misc {
        font_family = NovaMono
    }
